#!/usr/bin/env python
# -*- coding: utf-8 -*-
# By: Luke Craig 10/20/2017

from sys import version_info
if version_info > (3,0):
    print("¯\_(ツ)_/¯")
else:
    print(u"\u00af\_(\u30c4)_/\u00af".encode('utf-8'))
